import React, { useEffect, useState } from 'react'
import "./ScrollIndicator.css"
const ScrollIndicator = () => {
    const [ScrollTop, setScrollTop] = useState(0)
    const onScroll = (() => {
        const WinScroll = document.documentElement.ScrollTop;
        const Height = document.documentElement.scrollHeight - document.documentElement.clientHeight
        const Scrolled = (WinScroll / Height) * 100;
        setScrollTop(Scrolled)
    })
    useEffect(() => {
        window.addEventListener("scroll", onScroll)
        return () => window.removeEventListener("scroll", onScroll);
    }, [])
    return (
        <div>
            <div className="progressmainwrapper">
                <div className="progressmainstyle" style={{ width: `${ScrollTop}%` }}></div>
            </div>
            <h1>ScrollIndicator</h1>
            <p>
                When I actually said it though, I had been watching a whole lot of Instagram videos. Like, did you see what Jim Carrey did? Like Jim Carrey came out of nowhere, and was just like, "I was in solitude," and just like, I'm it now. I did some coaching on the plane, myself. I helped Brad, I helped Coach Stevens with some coaching. It was all an exploitation tactic. It literally spun the world — your guy's world — it spun it into a frenzy and proved exactly what I thought it would do in terms of how all this works. My light Brothers and Sisters! The age of No More Secrets is upon us.

                The only intent was just to wake up and do our research. Oh, if you're very much woke, there is no such thing as distractions. I see you. I see everyone. More than just your physical presence, I see your energy. I feel it. I know it. This is not even a conspiracy theory. The Earth is flat. It’s right in front of our faces. All I do is sit at home and watch Netflix.
                When I actually said it though, I had been watching a whole lot of Instagram videos. There comes a time where you mature as an individual, it's time to make that decision, and there is no looking back from that standpoint. Directors tell me what to do, and I kind of just put my own twist to it, just to get inside my personality that everybody doesn’t really get to see – my off-the-court interests and the way I act. It’s just me. In actuality, it really doesn't mean anything. It doesn't really get me up in the morning every single day to want to meditate, to want to read, to want to do things that fulfill my life. I'm not here to tirade anybody.

                Basketball, this life, it's an illusion in terms of certain material things that mean a lot more. If you ask me about basketball, I will talk all day. It created a division, or, literally stand up there and let all these people threw tomatoes at me, or have somebody think I'm somehow a different intellectual person because I believe that the Earth is flat and you think the world is round. It created exactly that. I have a presence and aura about me that’s very reality-based. It didn’t come in the form of living in this false world and not being able to tell the truth to somebody. And it connected me more to Nikola Tesla, and then I started taking, you know, just specific individuals throughout history that have been telling us things that just either they perish before their time or they were supposedly taken out or something that they said was just so thought-provoking that it just - they went from a genius to being a crazy person.

                The fact that they can make all these movies with alien descriptions. They’re not just going on strictly brainpower and this is just creative things that we’re going to put out to everybody. For what? All to put an alien movie out, for what? I’ve been playing basketball a lot longer than some of these people analyzing the game. I wanted to just ask other individuals, like do you really think this actually happened? I just wanna know. Because I don't know either. Like, did you see what Jim Carrey did? Like Jim Carrey came out of nowhere, and was just like, "I was in solitude," and just like, I'm it now. Dinosaurs - They find one bone and make up 98 percent of it digitally.
                I want to be on the cover of GQ, that's a personal goal. I want to be interviewed by GQ on camera and I want to do a freestyle for GQ like Drake. This is not even a conspiracy theory. The Earth is flat. It’s right in front of our faces. Like why do I have to wait for anybody? I don't really necessarily think of Christmas as a holiday. Spiritual alchemy is something that I'm huge in.

                I've been seeing the all-seeing eye for about six months now. Like all the time. Dinosaurs - They find one bone and make up 98 percent of it digitally. I won’t sit here and say that I know. But when I started actually doing research on my own and figuring out that there is no real picture of Earth – there is not one picture of Earth. Basketball, this life, it's an illusion in terms of certain material things that mean a lot more. Once you become awake, you don’t see that stuff anymore.

                Eye only know the best for Me. There is a certain aspect of life in which I want to tell people about, which is this true journey of really becoming a complete individual and total freedom of thought. I feel absolutely amazing. My energy, my sleeping patterns, just my intellect and everything that I'm awake to now — I'm very much aware. When the ball doesn’t go in the rim, the energy of the basketball can translate into the other end as well. That’s just basketball 101. Basketball isn’t a game; It’s an art form. You master the fundamentals so you can forget ’em, so you can improvise and just concentrate on what really matters: getting buckets.

                Like, I'll actually go and try to do the research on the scientific side and figure that out. You tell me who filmed, I’m asking you like this. Do you know they filmed the actual spacecraft leaving from the moon, right? Who the hell is filming that? You tell me. The fact that they can make all these movies with alien descriptions. They’re not just going on strictly brainpower and this is just creative things that we’re going to put out to everybody. For what? All to put an alien movie out, for what? I’m probably one of the most competitive people ever. I wanted to just ask other individuals, like do you really think this actually happened? I just wanna know. Because I don't know either.
                My light Brothers and Sisters! The age of No More Secrets is upon us. I can't even call them conspiracy theories, because some of the things of just logic and common knowledge are just there. Oh, if you're very much woke, there is no such thing as distractions. All I want to do is be able to have that open conversation. Brad fits perfectly in terms of that because he has an intellectual mind and is an intellectual human being. It was something I was unbelievably craving in terms of what I wanted for my career.

                And I felt like ever since I took meditation to another level and figuring out the research behind that, and figuring out how knowledgable I can become, and just being enriched in that, enriched in my soul, rather than realizing that this physical realm that I live in and I exist in is the only thing that's available to me, you know. I feel absolutely amazing. My energy, my sleeping patterns, just my intellect and everything that I'm awake to now — I'm very much aware. I’m an actual genius when it comes to this game. I won’t sit here and say that I know. But when I started actually doing research on my own and figuring out that there is no real picture of Earth – there is not one picture of Earth. You tell me who filmed, I’m asking you like this. Do you know they filmed the actual spacecraft leaving from the moon, right? Who the hell is filming that? You tell me.

                What’s his name? Was it Neil Armstrong? I don’t even know. Directors tell me what to do, and I kind of just put my own twist to it, just to get inside my personality that everybody doesn’t really get to see – my off-the-court interests and the way I act. It’s just me. I've seen a lot of things that my educational system has said that was real that turned out to be completely fake. All these things that they keep giving to us, all this information, I’m just saying that these things that used to put me in fear, it makes you not want to question it naturally, because of how much information you actually can figure out and how much information there actually is out there. It’s crazy. Dinosaurs - They find one bone and make up 98 percent of it digitally.

                And it almost felt like I was standing on top of a pendulum and I was like swinging back and forth and then it gave everyone a chance to just look at me and then, if they didn’t agree with me, kind of like throw rocks at me. When the ball doesn’t go in the rim, the energy of the basketball can translate into the other end as well. That’s just basketball 101. Like, I'll actually go and try to do the research on the scientific side and figure that out. The fact that they can make all these movies with alien descriptions. They’re not just going on strictly brainpower and this is just creative things that we’re going to put out to everybody. For what? All to put an alien movie out, for what? What does the word "government" mean to you?

                The only thing I command is respect. I stand for four things, man. Inner peace. Freedom. Equality and World Peace. So, if that is being conflicted inside of me, I am definitely going to have something to say. I did some coaching on the plane, myself. I helped Brad, I helped Coach Stevens with some coaching. I see you. I see everyone. More than just your physical presence, I see your energy. I feel it. I know it. I’ve been playing basketball a lot longer than some of these people analyzing the game.
                Once you become awake, you don’t see that stuff anymore. I see you. I see everyone. More than just your physical presence, I see your energy. I feel it. I know it. The hoopla on Christmas, I don't really get into that. I did some coaching on the plane, myself. I helped Brad, I helped Coach Stevens with some coaching. There comes a time where you mature as an individual, it's time to make that decision, and there is no looking back from that standpoint.

                They’re particularly putting you in the direction of what to believe and what not to believe. I Am My True Self. Are you? Dinosaurs - They find one bone and make up 98 percent of it digitally. Oh, if you're very much woke, there is no such thing as distractions. I stand for four things, man. Inner peace. Freedom. Equality and World Peace. So, if that is being conflicted inside of me, I am definitely going to have something to say.

                Naturally, sometimes the ego or naturally my personality will get in the way, of pushing people away rather than bringing them closer and learning more about them. There is a certain aspect of life in which I want to tell people about, which is this true journey of really becoming a complete individual and total freedom of thought. So I don't just limit myself to being in the circle of like "This is what you believe in." I'm not here to tirade anybody. I’m an actual genius when it comes to this game.

                There is no time to figure out how to save somebody's feelings when ultimately you have to be selfish in figuring out what you want to do. I’m not eating a whole bunch of animals anymore. The truth is right there, you just got to go searching for it. Basketball, this life, it's an illusion in terms of certain material things that mean a lot more. Like why do I have to wait for anybody?

                I thought it was interesting in "The Alchemist" how he was looking for the alchemist but the alchemist found him. Found him in the middle of the desert with this and it's just like, "I can't believe I just met him," and in doing so sometimes meeting certain individuals, they embody so much of that wisdom that they want to impart on you. Brad fits perfectly in terms of that because he has an intellectual mind and is an intellectual human being. It was something I was unbelievably craving in terms of what I wanted for my career. I want to be on the cover of GQ, that's a personal goal. I want to be interviewed by GQ on camera and I want to do a freestyle for GQ like Drake. I've been seeing the all-seeing eye for about six months now. Like all the time. I wanted to just ask other individuals, like do you really think this actually happened? I just wanna know. Because I don't know either.

                All these things that they keep giving to us, all this information, I’m just saying that these things that used to put me in fear, it makes you not want to question it naturally, because of how much information you actually can figure out and how much information there actually is out there. It’s crazy. In actuality, it really doesn't mean anything. It doesn't really get me up in the morning every single day to want to meditate, to want to read, to want to do things that fulfill my life. Eye only know the best for Me. Spiritual alchemy is something that I'm huge in. I can't even call them conspiracy theories, because some of the things of just logic and common knowledge are just there.
                All these things that they keep giving to us, all this information, I’m just saying that these things that used to put me in fear, it makes you not want to question it naturally, because of how much information you actually can figure out and how much information there actually is out there. It’s crazy. I’m an actual genius when it comes to this game. There is no time to figure out how to save somebody's feelings when ultimately you have to be selfish in figuring out what you want to do. Like why do I have to wait for anybody? Literally, as simple as this: Why is it that the the steps – in terms of the pictures that they say he stepped on – why do they look completely different than the ones that are actually in the museum that he walked with?

                So I don't just limit myself to being in the circle of like "This is what you believe in." And it connected me more to Nikola Tesla, and then I started taking, you know, just specific individuals throughout history that have been telling us things that just either they perish before their time or they were supposedly taken out or something that they said was just so thought-provoking that it just - they went from a genius to being a crazy person. Dinosaurs - They find one bone and make up 98 percent of it digitally. My light Brothers and Sisters! The age of No More Secrets is upon us. Basketball isn’t a game; It’s an art form. You master the fundamentals so you can forget ’em, so you can improvise and just concentrate on what really matters: getting buckets.

                I did some coaching on the plane, myself. I helped Brad, I helped Coach Stevens with some coaching. I won’t sit here and say that I know. But when I started actually doing research on my own and figuring out that there is no real picture of Earth – there is not one picture of Earth. There is a certain aspect of life in which I want to tell people about, which is this true journey of really becoming a complete individual and total freedom of thought. They’re particularly putting you in the direction of what to believe and what not to believe. I wanted to just ask other individuals, like do you really think this actually happened? I just wanna know. Because I don't know either.

                Everybody coming up to me like, "You know I gotta reteach my whole curriculum!" I’m sorry. I apologize. Spiritual alchemy is something that I'm huge in. All I do is sit at home and watch Netflix. The only intent was just to wake up and do our research. They always say, "truth is in plain sight," purposely though. Have you seen the new Taco Bell commercial?

                In actuality, it really doesn't mean anything. It doesn't really get me up in the morning every single day to want to meditate, to want to read, to want to do things that fulfill my life. What I’ve been taught is that the earth is round, but if you really think about it from a landscape of the way we travel, the way we move and the fact that, can you really think of us rotating around the sun and all planets aligned, rotating in specific dates, being perpendicular with what’s going on with these planets. I’ve been playing basketball a lot longer than some of these people analyzing the game. And it almost felt like I was standing on top of a pendulum and I was like swinging back and forth and then it gave everyone a chance to just look at me and then, if they didn’t agree with me, kind of like throw rocks at me. Eye see all.

                The hoopla on Christmas, I don't really get into that. The truth is right there, you just got to go searching for it. Like people think it’s an idea, and when you actually follow that idea and back it up with research of your own then you’re almost like convincing yourself like this didn’t happen you know what I mean. I made the decision as a man, and as a man over there, Max Kellerman, just respect it and leave it alone. My focus is basketball, and that’s it.

                I feel absolutely amazing. My energy, my sleeping patterns, just my intellect and everything that I'm awake to now — I'm very much aware. I thought it was interesting in "The Alchemist" how he was looking for the alchemist but the alchemist found him. Found him in the middle of the desert with this and it's just like, "I can't believe I just met him," and in doing so sometimes meeting certain individuals, they embody so much of that wisdom that they want to impart on you. What’s his name? Was it Neil Armstrong? I don’t even know. I Am My True Self. Are you? Eye only know the best for Me.
            </p>
        </div>
    )
}

export default ScrollIndicator